language: C++
sudo: false
dist: trusty
addons:
  apt:
    update: true
    sources:
      - llvm-toolchain-trusty-6.0
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libclang-6.0-dev
      - llvm-6.0-dev
      - gcc-4.9
      - g++-4.9
      - curl

install:
  - curl -fsS https://dlang.org/install.sh | bash -s ldc
  - source ~/dlang/ldc-1.12.0/activate
  - export CC="gcc-4.9"
  - export CPP="g++-4.9"
  - export CXX="g++-4.9"
  - export LD="g++-4.9"

script:
  - mkdir -p build
  - cd build
  - cmake .. -DCMAKE_PREFIX_PATH=/usr/lib/llvm-6.0 -DCMAKE_EXPORT_COMPILE_COMMANDS=OFF
  - make
  - cmake .. -DCMAKE_PREFIX_PATH=/usr/lib/llvm-6.0 -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
  - ln -s $PWD/compile_commands.json ../CPP2D_UT_CPP
  - cd ../CPP2D_UT_CPP
  - ../build/CPP2D/cpp2d stdlib_testsuite.cpp template_testsuite.cpp test.cpp framework.cpp main.cpp comment.cpp -macro-expr=UT_MACRO_EXPR/nn -macro-expr=CHECK/e -macro-expr=CHECK_EQUAL/ee -macro-expr=UT_MACRO/eee -macro-stmt=UT_MACRO_STMT -macro-stmt=UT_MACRO_STMT_CLASS/ntne
  - mkdir ../CPP2D_UT_D
  - cp ../build/CPP2D_UT_CPP/*.d ../CPP2D_UT_D
  - cd ../CPP2D_UT_D
  - ldc2 -m64 -ofCPP2D_UT_D ../cpp_std.d template_testsuite.d main.d framework.d test.d stdlib_testsuite.d comment.d
  - ../build/CPP2D_UT_CPP/CPP2D_UT_CPP
  - ./CPP2D_UT_D
